[package]
name = "gpoddersync"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
warp = "0.3"
# bytes = "1.1.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
