[package]
name = "podsync"
version = "0.1.0"
edition = "2021"

description = "A server to sync podcasts with, mirroring the gpodder API. Designed for use with AntennaPod"
license = "GPL-3.0-or-later"
homepage = "https://github.com/bobrippling/podsync"
repository = "https://github.com/bobrippling/podsync"

[dependencies]
tokio = { version = "1.26.0", features = ["full"] }
serde = { version = "1.0.152", features = ["derive"] }
warp = "0.3.3"
# bytes = "1.1.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
time = { version = "0.3.20", features = ["serde", "formatting", "parsing", "macros"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "sqlite", "time", "offline"]}
# sqlx-cli
base64_light = "0.1.5"
sha256 = "1.1.2"
uuid = { version = "1.3.0", features = ["v4"] }
