name: Publish to crates.io

on:
  workflow_run:
    workflows: ["podsync release"]
    types:
      - completed

jobs:
  publish:
    name: Publish crate
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Publish
        # uses CARGO_REGISTRY_TOKEN
        run: cargo publish
